services:

  redis:
    image: redis:alpine
    container_name: flood-redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    container_name: flood-backend
    ports:
      - "3002:3002"
    env_file:
      - ./backend/.env
    environment:
      - AI_SERVICE_URL=http://ai-service:8000
      - REDIS_URL=redis://redis:6379
    depends_on:
      ai-service:
        condition: service_healthy
      redis:
        condition: service_started

  ai-service:
    build:
      context: ./ai_service
    container_name: flood-ai
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  frontend:
    build:
      context: ./flood-prediction-frontend/flood-prediction-system-ui
    container_name: flood-frontend
    ports:
      - "5173:80"
    depends_on:
      backend:
        condition: service_started
