require('dotenv').config()
const { Pool } = require('pg')
const p = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } })
p.query("SELECT tablename FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename")
  .then(r => { console.log('Tables:', r.rows.map(x => x.tablename)); p.end() })
  .catch(e => { console.error(e.message); p.end() })
